# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: thrippy/v1/credentials.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'thrippy/v1/credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cthrippy/v1/credentials.proto\x12\nthrippy.v1\x1a\x1fgoogle/api/field_behavior.proto\"j\n\x0f\x43redentialField\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05links\x18\x03 \x03(\t\x12\x0e\n\x06manual\x18\x04 \x01(\x08\x12\x10\n\x08optional\x18\x05 \x01(\x08\x42+Z)github.com/tzrikka/thrippy-api/thrippy/v1b\x08\x65\x64itionsp\xe9\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thrippy.v1.credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/tzrikka/thrippy-api/thrippy/v1'
  _globals['_CREDENTIALFIELD'].fields_by_name['name']._loaded_options = None
  _globals['_CREDENTIALFIELD'].fields_by_name['name']._serialized_options = b'\340A\002'
  _globals['_CREDENTIALFIELD']._serialized_start=77
  _globals['_CREDENTIALFIELD']._serialized_end=183
# @@protoc_insertion_point(module_scope)
