# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from thrippy.v1 import thrippy_pb2 as thrippy_dot_v1_dot_thrippy__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in thrippy/v1/thrippy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ThrippyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLink = channel.unary_unary(
                '/thrippy.v1.ThrippyService/CreateLink',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.CreateLinkRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.CreateLinkResponse.FromString,
                _registered_method=True)
        self.GetLink = channel.unary_unary(
                '/thrippy.v1.ThrippyService/GetLink',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.GetLinkRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.GetLinkResponse.FromString,
                _registered_method=True)
        self.DeleteLink = channel.unary_unary(
                '/thrippy.v1.ThrippyService/DeleteLink',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteLinkRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteLinkResponse.FromString,
                _registered_method=True)
        self.SetCredentials = channel.unary_unary(
                '/thrippy.v1.ThrippyService/SetCredentials',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.SetCredentialsRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.SetCredentialsResponse.FromString,
                _registered_method=True)
        self.GetCredentials = channel.unary_unary(
                '/thrippy.v1.ThrippyService/GetCredentials',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.GetCredentialsRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.GetCredentialsResponse.FromString,
                _registered_method=True)
        self.DeleteCredentials = channel.unary_unary(
                '/thrippy.v1.ThrippyService/DeleteCredentials',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteCredentialsRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteCredentialsResponse.FromString,
                _registered_method=True)
        self.SetMetadata = channel.unary_unary(
                '/thrippy.v1.ThrippyService/SetMetadata',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.SetMetadataRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.SetMetadataResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/thrippy.v1.ThrippyService/GetMetadata',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteMetadata = channel.unary_unary(
                '/thrippy.v1.ThrippyService/DeleteMetadata',
                request_serializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteMetadataRequest.SerializeToString,
                response_deserializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteMetadataResponse.FromString,
                _registered_method=True)


class ThrippyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ThrippyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLink,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.CreateLinkRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.CreateLinkResponse.SerializeToString,
            ),
            'GetLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLink,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.GetLinkRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.GetLinkResponse.SerializeToString,
            ),
            'DeleteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLink,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteLinkRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteLinkResponse.SerializeToString,
            ),
            'SetCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCredentials,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.SetCredentialsRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.SetCredentialsResponse.SerializeToString,
            ),
            'GetCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentials,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.GetCredentialsRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.GetCredentialsResponse.SerializeToString,
            ),
            'DeleteCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredentials,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteCredentialsRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteCredentialsResponse.SerializeToString,
            ),
            'SetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMetadata,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.SetMetadataRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.SetMetadataResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.GetMetadataRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.GetMetadataResponse.SerializeToString,
            ),
            'DeleteMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMetadata,
                    request_deserializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteMetadataRequest.FromString,
                    response_serializer=thrippy_dot_v1_dot_thrippy__pb2.DeleteMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thrippy.v1.ThrippyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thrippy.v1.ThrippyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ThrippyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/CreateLink',
            thrippy_dot_v1_dot_thrippy__pb2.CreateLinkRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.CreateLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/GetLink',
            thrippy_dot_v1_dot_thrippy__pb2.GetLinkRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.GetLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/DeleteLink',
            thrippy_dot_v1_dot_thrippy__pb2.DeleteLinkRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.DeleteLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/SetCredentials',
            thrippy_dot_v1_dot_thrippy__pb2.SetCredentialsRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.SetCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/GetCredentials',
            thrippy_dot_v1_dot_thrippy__pb2.GetCredentialsRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.GetCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/DeleteCredentials',
            thrippy_dot_v1_dot_thrippy__pb2.DeleteCredentialsRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.DeleteCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/SetMetadata',
            thrippy_dot_v1_dot_thrippy__pb2.SetMetadataRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.SetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/GetMetadata',
            thrippy_dot_v1_dot_thrippy__pb2.GetMetadataRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thrippy.v1.ThrippyService/DeleteMetadata',
            thrippy_dot_v1_dot_thrippy__pb2.DeleteMetadataRequest.SerializeToString,
            thrippy_dot_v1_dot_thrippy__pb2.DeleteMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
