// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: thrippy/v1/credentials.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialField struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Links       []string               `protobuf:"bytes,3,rep,name=links"`
	xxx_hidden_Manual      bool                   `protobuf:"varint,4,opt,name=manual"`
	xxx_hidden_Optional    bool                   `protobuf:"varint,5,opt,name=optional"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CredentialField) Reset() {
	*x = CredentialField{}
	mi := &file_thrippy_v1_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialField) ProtoMessage() {}

func (x *CredentialField) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CredentialField) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CredentialField) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CredentialField) GetLinks() []string {
	if x != nil {
		return x.xxx_hidden_Links
	}
	return nil
}

func (x *CredentialField) GetManual() bool {
	if x != nil {
		return x.xxx_hidden_Manual
	}
	return false
}

func (x *CredentialField) GetOptional() bool {
	if x != nil {
		return x.xxx_hidden_Optional
	}
	return false
}

func (x *CredentialField) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CredentialField) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CredentialField) SetLinks(v []string) {
	x.xxx_hidden_Links = v
}

func (x *CredentialField) SetManual(v bool) {
	x.xxx_hidden_Manual = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CredentialField) SetOptional(v bool) {
	x.xxx_hidden_Optional = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *CredentialField) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CredentialField) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CredentialField) HasManual() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CredentialField) HasOptional() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CredentialField) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *CredentialField) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *CredentialField) ClearManual() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Manual = false
}

func (x *CredentialField) ClearOptional() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Optional = false
}

type CredentialField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        *string
	Description *string
	Links       []string
	Manual      *bool
	Optional    *bool
}

func (b0 CredentialField_builder) Build() *CredentialField {
	m0 := &CredentialField{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_Links = b.Links
	if b.Manual != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Manual = *b.Manual
	}
	if b.Optional != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Optional = *b.Optional
	}
	return m0
}

var File_thrippy_v1_credentials_proto protoreflect.FileDescriptor

const file_thrippy_v1_credentials_proto_rawDesc = "" +
	"\n" +
	"\x1cthrippy/v1/credentials.proto\x12\n" +
	"thrippy.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a!google/protobuf/go_features.proto\"\x96\x01\n" +
	"\x0fCredentialField\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05links\x18\x03 \x03(\tR\x05links\x12\x16\n" +
	"\x06manual\x18\x04 \x01(\bR\x06manual\x12\x1a\n" +
	"\boptional\x18\x05 \x01(\bR\boptionalB3Z)github.com/tzrikka/thrippy-api/thrippy/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_thrippy_v1_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_thrippy_v1_credentials_proto_goTypes = []any{
	(*CredentialField)(nil), // 0: thrippy.v1.CredentialField
}
var file_thrippy_v1_credentials_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thrippy_v1_credentials_proto_init() }
func file_thrippy_v1_credentials_proto_init() {
	if File_thrippy_v1_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thrippy_v1_credentials_proto_rawDesc), len(file_thrippy_v1_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thrippy_v1_credentials_proto_goTypes,
		DependencyIndexes: file_thrippy_v1_credentials_proto_depIdxs,
		MessageInfos:      file_thrippy_v1_credentials_proto_msgTypes,
	}.Build()
	File_thrippy_v1_credentials_proto = out.File
	file_thrippy_v1_credentials_proto_goTypes = nil
	file_thrippy_v1_credentials_proto_depIdxs = nil
}
