// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: thrippy/v1/oauth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OAuthConfig struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AuthUrl      *string                `protobuf:"bytes,1,opt,name=auth_url,json=access_url"`
	xxx_hidden_TokenUrl     *string                `protobuf:"bytes,3,opt,name=token_url"`
	xxx_hidden_AuthStyle    int64                  `protobuf:"varint,4,opt,name=auth_style"`
	xxx_hidden_ClientId     *string                `protobuf:"bytes,5,opt,name=client_id"`
	xxx_hidden_ClientSecret *string                `protobuf:"bytes,6,opt,name=client_secret"`
	xxx_hidden_Scopes       []string               `protobuf:"bytes,8,rep,name=scopes"`
	xxx_hidden_AuthCodes    map[string]string      `protobuf:"bytes,9,rep,name=auth_codes" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Params       map[string]string      `protobuf:"bytes,10,rep,name=params" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OAuthConfig) Reset() {
	*x = OAuthConfig{}
	mi := &file_thrippy_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthConfig) ProtoMessage() {}

func (x *OAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OAuthConfig) GetAuthUrl() string {
	if x != nil {
		if x.xxx_hidden_AuthUrl != nil {
			return *x.xxx_hidden_AuthUrl
		}
		return ""
	}
	return ""
}

func (x *OAuthConfig) GetTokenUrl() string {
	if x != nil {
		if x.xxx_hidden_TokenUrl != nil {
			return *x.xxx_hidden_TokenUrl
		}
		return ""
	}
	return ""
}

func (x *OAuthConfig) GetAuthStyle() int64 {
	if x != nil {
		return x.xxx_hidden_AuthStyle
	}
	return 0
}

func (x *OAuthConfig) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *OAuthConfig) GetClientSecret() string {
	if x != nil {
		if x.xxx_hidden_ClientSecret != nil {
			return *x.xxx_hidden_ClientSecret
		}
		return ""
	}
	return ""
}

func (x *OAuthConfig) GetScopes() []string {
	if x != nil {
		return x.xxx_hidden_Scopes
	}
	return nil
}

func (x *OAuthConfig) GetAuthCodes() map[string]string {
	if x != nil {
		return x.xxx_hidden_AuthCodes
	}
	return nil
}

func (x *OAuthConfig) GetParams() map[string]string {
	if x != nil {
		return x.xxx_hidden_Params
	}
	return nil
}

func (x *OAuthConfig) SetAuthUrl(v string) {
	x.xxx_hidden_AuthUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *OAuthConfig) SetTokenUrl(v string) {
	x.xxx_hidden_TokenUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *OAuthConfig) SetAuthStyle(v int64) {
	x.xxx_hidden_AuthStyle = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *OAuthConfig) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *OAuthConfig) SetClientSecret(v string) {
	x.xxx_hidden_ClientSecret = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *OAuthConfig) SetScopes(v []string) {
	x.xxx_hidden_Scopes = v
}

func (x *OAuthConfig) SetAuthCodes(v map[string]string) {
	x.xxx_hidden_AuthCodes = v
}

func (x *OAuthConfig) SetParams(v map[string]string) {
	x.xxx_hidden_Params = v
}

func (x *OAuthConfig) HasAuthUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OAuthConfig) HasTokenUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OAuthConfig) HasAuthStyle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OAuthConfig) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OAuthConfig) HasClientSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OAuthConfig) ClearAuthUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AuthUrl = nil
}

func (x *OAuthConfig) ClearTokenUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TokenUrl = nil
}

func (x *OAuthConfig) ClearAuthStyle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AuthStyle = 0
}

func (x *OAuthConfig) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ClientId = nil
}

func (x *OAuthConfig) ClearClientSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ClientSecret = nil
}

type OAuthConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AuthUrl      *string
	TokenUrl     *string
	AuthStyle    *int64
	ClientId     *string
	ClientSecret *string
	Scopes       []string
	AuthCodes    map[string]string
	Params       map[string]string
}

func (b0 OAuthConfig_builder) Build() *OAuthConfig {
	m0 := &OAuthConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AuthUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_AuthUrl = b.AuthUrl
	}
	if b.TokenUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_TokenUrl = b.TokenUrl
	}
	if b.AuthStyle != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_AuthStyle = *b.AuthStyle
	}
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_ClientId = b.ClientId
	}
	if b.ClientSecret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_ClientSecret = b.ClientSecret
	}
	x.xxx_hidden_Scopes = b.Scopes
	x.xxx_hidden_AuthCodes = b.AuthCodes
	x.xxx_hidden_Params = b.Params
	return m0
}

// Based on https://pkg.go.dev/golang.org/x/oauth2#Token.
type OAuthToken struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken  *string                `protobuf:"bytes,1,opt,name=access_token"`
	xxx_hidden_Expiry       *string                `protobuf:"bytes,2,opt,name=expiry"`
	xxx_hidden_RefreshToken *string                `protobuf:"bytes,3,opt,name=refresh_token"`
	xxx_hidden_TokenType    *string                `protobuf:"bytes,4,opt,name=token_type"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OAuthToken) Reset() {
	*x = OAuthToken{}
	mi := &file_thrippy_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthToken) ProtoMessage() {}

func (x *OAuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OAuthToken) GetAccessToken() string {
	if x != nil {
		if x.xxx_hidden_AccessToken != nil {
			return *x.xxx_hidden_AccessToken
		}
		return ""
	}
	return ""
}

func (x *OAuthToken) GetExpiry() string {
	if x != nil {
		if x.xxx_hidden_Expiry != nil {
			return *x.xxx_hidden_Expiry
		}
		return ""
	}
	return ""
}

func (x *OAuthToken) GetRefreshToken() string {
	if x != nil {
		if x.xxx_hidden_RefreshToken != nil {
			return *x.xxx_hidden_RefreshToken
		}
		return ""
	}
	return ""
}

func (x *OAuthToken) GetTokenType() string {
	if x != nil {
		if x.xxx_hidden_TokenType != nil {
			return *x.xxx_hidden_TokenType
		}
		return ""
	}
	return ""
}

func (x *OAuthToken) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *OAuthToken) SetExpiry(v string) {
	x.xxx_hidden_Expiry = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *OAuthToken) SetRefreshToken(v string) {
	x.xxx_hidden_RefreshToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *OAuthToken) SetTokenType(v string) {
	x.xxx_hidden_TokenType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *OAuthToken) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OAuthToken) HasExpiry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OAuthToken) HasRefreshToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OAuthToken) HasTokenType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OAuthToken) ClearAccessToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AccessToken = nil
}

func (x *OAuthToken) ClearExpiry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Expiry = nil
}

func (x *OAuthToken) ClearRefreshToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RefreshToken = nil
}

func (x *OAuthToken) ClearTokenType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TokenType = nil
}

type OAuthToken_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken  *string
	Expiry       *string
	RefreshToken *string
	TokenType    *string
}

func (b0 OAuthToken_builder) Build() *OAuthToken {
	m0 := &OAuthToken{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AccessToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_AccessToken = b.AccessToken
	}
	if b.Expiry != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Expiry = b.Expiry
	}
	if b.RefreshToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RefreshToken = b.RefreshToken
	}
	if b.TokenType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_TokenType = b.TokenType
	}
	return m0
}

var File_thrippy_v1_oauth_proto protoreflect.FileDescriptor

const file_thrippy_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"\x16thrippy/v1/oauth.proto\x12\n" +
	"thrippy.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a!google/protobuf/go_features.proto\"\xe3\x03\n" +
	"\vOAuthConfig\x12!\n" +
	"\bauth_url\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"access_url\x12!\n" +
	"\ttoken_url\x18\x03 \x01(\tB\x03\xe0A\x02R\ttoken_url\x12\x1e\n" +
	"\n" +
	"auth_style\x18\x04 \x01(\x03R\n" +
	"auth_style\x12!\n" +
	"\tclient_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tclient_id\x12)\n" +
	"\rclient_secret\x18\x06 \x01(\tB\x03\xe0A\x02R\rclient_secret\x12\x16\n" +
	"\x06scopes\x18\b \x03(\tR\x06scopes\x12F\n" +
	"\n" +
	"auth_codes\x18\t \x03(\v2&.thrippy.v1.OAuthConfig.AuthCodesEntryR\n" +
	"auth_codes\x12;\n" +
	"\x06params\x18\n" +
	" \x03(\v2#.thrippy.v1.OAuthConfig.ParamsEntryR\x06params\x1a<\n" +
	"\x0eAuthCodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03J\x04\b\a\x10\b\"\x8e\x01\n" +
	"\n" +
	"OAuthToken\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\tR\x06expiry\x12$\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\rrefresh_token\x12\x1e\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\n" +
	"token_typeB3Z)github.com/tzrikka/thrippy-api/thrippy/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_thrippy_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_thrippy_v1_oauth_proto_goTypes = []any{
	(*OAuthConfig)(nil), // 0: thrippy.v1.OAuthConfig
	(*OAuthToken)(nil),  // 1: thrippy.v1.OAuthToken
	nil,                 // 2: thrippy.v1.OAuthConfig.AuthCodesEntry
	nil,                 // 3: thrippy.v1.OAuthConfig.ParamsEntry
}
var file_thrippy_v1_oauth_proto_depIdxs = []int32{
	2, // 0: thrippy.v1.OAuthConfig.auth_codes:type_name -> thrippy.v1.OAuthConfig.AuthCodesEntry
	3, // 1: thrippy.v1.OAuthConfig.params:type_name -> thrippy.v1.OAuthConfig.ParamsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_thrippy_v1_oauth_proto_init() }
func file_thrippy_v1_oauth_proto_init() {
	if File_thrippy_v1_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thrippy_v1_oauth_proto_rawDesc), len(file_thrippy_v1_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thrippy_v1_oauth_proto_goTypes,
		DependencyIndexes: file_thrippy_v1_oauth_proto_depIdxs,
		MessageInfos:      file_thrippy_v1_oauth_proto_msgTypes,
	}.Build()
	File_thrippy_v1_oauth_proto = out.File
	file_thrippy_v1_oauth_proto_goTypes = nil
	file_thrippy_v1_oauth_proto_depIdxs = nil
}
