// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: thrippy/v1/thrippy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Template    *string                `protobuf:"bytes,1,opt,name=template"`
	xxx_hidden_OauthConfig *OAuthConfig           `protobuf:"bytes,2,opt,name=oauth_config,json=oauthConfig"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateLinkRequest) GetTemplate() string {
	if x != nil {
		if x.xxx_hidden_Template != nil {
			return *x.xxx_hidden_Template
		}
		return ""
	}
	return ""
}

func (x *CreateLinkRequest) GetOauthConfig() *OAuthConfig {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_OauthConfig) {
				protoimpl.X.UnmarshalField(x, 2)
			}
			var rv *OAuthConfig
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_OauthConfig), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *CreateLinkRequest) SetTemplate(v string) {
	x.xxx_hidden_Template = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateLinkRequest) SetOauthConfig(v *OAuthConfig) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_OauthConfig, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
	}
}

func (x *CreateLinkRequest) HasTemplate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateLinkRequest) HasOauthConfig() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateLinkRequest) ClearTemplate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Template = nil
}

func (x *CreateLinkRequest) ClearOauthConfig() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_OauthConfig, (*OAuthConfig)(nil))
}

type CreateLinkRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Template    *string
	OauthConfig *OAuthConfig
}

func (b0 CreateLinkRequest_builder) Build() *CreateLinkRequest {
	m0 := &CreateLinkRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Template != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Template = b.Template
	}
	if b.OauthConfig != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_OauthConfig = b.OauthConfig
	}
	return m0
}

type CreateLinkResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId           *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	xxx_hidden_CredentialFields *[]*CredentialField    `protobuf:"bytes,2,rep,name=credential_fields,json=credentialFields"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateLinkResponse) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *CreateLinkResponse) GetCredentialFields() []*CredentialField {
	if x != nil {
		if x.xxx_hidden_CredentialFields != nil {
			return *x.xxx_hidden_CredentialFields
		}
	}
	return nil
}

func (x *CreateLinkResponse) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateLinkResponse) SetCredentialFields(v []*CredentialField) {
	x.xxx_hidden_CredentialFields = &v
}

func (x *CreateLinkResponse) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateLinkResponse) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

type CreateLinkResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId           *string
	CredentialFields []*CredentialField
}

func (b0 CreateLinkResponse_builder) Build() *CreateLinkResponse {
	m0 := &CreateLinkResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_LinkId = b.LinkId
	}
	x.xxx_hidden_CredentialFields = &b.CredentialFields
	return m0
}

type GetLinkRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId      *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetLinkRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *GetLinkRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetLinkRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetLinkRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

type GetLinkRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId *string
}

func (b0 GetLinkRequest_builder) Build() *GetLinkRequest {
	m0 := &GetLinkRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_LinkId = b.LinkId
	}
	return m0
}

type GetLinkResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Template         *string                `protobuf:"bytes,1,opt,name=template"`
	xxx_hidden_OauthConfig      *OAuthConfig           `protobuf:"bytes,2,opt,name=oauth_config,json=oauthConfig"`
	xxx_hidden_CredentialFields *[]*CredentialField    `protobuf:"bytes,3,rep,name=credential_fields,json=credentialFields"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetLinkResponse) GetTemplate() string {
	if x != nil {
		if x.xxx_hidden_Template != nil {
			return *x.xxx_hidden_Template
		}
		return ""
	}
	return ""
}

func (x *GetLinkResponse) GetOauthConfig() *OAuthConfig {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_OauthConfig) {
				protoimpl.X.UnmarshalField(x, 2)
			}
			var rv *OAuthConfig
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_OauthConfig), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *GetLinkResponse) GetCredentialFields() []*CredentialField {
	if x != nil {
		if x.xxx_hidden_CredentialFields != nil {
			return *x.xxx_hidden_CredentialFields
		}
	}
	return nil
}

func (x *GetLinkResponse) SetTemplate(v string) {
	x.xxx_hidden_Template = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *GetLinkResponse) SetOauthConfig(v *OAuthConfig) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_OauthConfig, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
	}
}

func (x *GetLinkResponse) SetCredentialFields(v []*CredentialField) {
	x.xxx_hidden_CredentialFields = &v
}

func (x *GetLinkResponse) HasTemplate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetLinkResponse) HasOauthConfig() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetLinkResponse) ClearTemplate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Template = nil
}

func (x *GetLinkResponse) ClearOauthConfig() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_OauthConfig, (*OAuthConfig)(nil))
}

type GetLinkResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Template         *string
	OauthConfig      *OAuthConfig
	CredentialFields []*CredentialField
}

func (b0 GetLinkResponse_builder) Build() *GetLinkResponse {
	m0 := &GetLinkResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Template != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Template = b.Template
	}
	if b.OauthConfig != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_OauthConfig = b.OauthConfig
	}
	x.xxx_hidden_CredentialFields = &b.CredentialFields
	return m0
}

type DeleteLinkRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId       *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	xxx_hidden_AllowMissing bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteLinkRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *DeleteLinkRequest) GetAllowMissing() bool {
	if x != nil {
		return x.xxx_hidden_AllowMissing
	}
	return false
}

func (x *DeleteLinkRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeleteLinkRequest) SetAllowMissing(v bool) {
	x.xxx_hidden_AllowMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteLinkRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteLinkRequest) HasAllowMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteLinkRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

func (x *DeleteLinkRequest) ClearAllowMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllowMissing = false
}

type DeleteLinkRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId       *string
	AllowMissing *bool
}

func (b0 DeleteLinkRequest_builder) Build() *DeleteLinkRequest {
	m0 := &DeleteLinkRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_LinkId = b.LinkId
	}
	if b.AllowMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AllowMissing = *b.AllowMissing
	}
	return m0
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteLinkResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteLinkResponse_builder) Build() *DeleteLinkResponse {
	m0 := &DeleteLinkResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetCredentialsRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId       *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	xxx_hidden_GenericCreds map[string]string      `protobuf:"bytes,2,rep,name=generic_creds,json=genericCreds" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Token        *OAuthToken            `protobuf:"bytes,3,opt,name=token"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetCredentialsRequest) Reset() {
	*x = SetCredentialsRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCredentialsRequest) ProtoMessage() {}

func (x *SetCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetCredentialsRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *SetCredentialsRequest) GetGenericCreds() map[string]string {
	if x != nil {
		return x.xxx_hidden_GenericCreds
	}
	return nil
}

func (x *SetCredentialsRequest) GetToken() *OAuthToken {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return nil
}

func (x *SetCredentialsRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SetCredentialsRequest) SetGenericCreds(v map[string]string) {
	x.xxx_hidden_GenericCreds = v
}

func (x *SetCredentialsRequest) SetToken(v *OAuthToken) {
	x.xxx_hidden_Token = v
}

func (x *SetCredentialsRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetCredentialsRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Token != nil
}

func (x *SetCredentialsRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

func (x *SetCredentialsRequest) ClearToken() {
	x.xxx_hidden_Token = nil
}

type SetCredentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId       *string
	GenericCreds map[string]string
	Token        *OAuthToken
}

func (b0 SetCredentialsRequest_builder) Build() *SetCredentialsRequest {
	m0 := &SetCredentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_LinkId = b.LinkId
	}
	x.xxx_hidden_GenericCreds = b.GenericCreds
	x.xxx_hidden_Token = b.Token
	return m0
}

type SetCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCredentialsResponse) Reset() {
	*x = SetCredentialsResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCredentialsResponse) ProtoMessage() {}

func (x *SetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetCredentialsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetCredentialsResponse_builder) Build() *SetCredentialsResponse {
	m0 := &SetCredentialsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetCredentialsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId      *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCredentialsRequest) Reset() {
	*x = GetCredentialsRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsRequest) ProtoMessage() {}

func (x *GetCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCredentialsRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *GetCredentialsRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetCredentialsRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetCredentialsRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

type GetCredentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId *string
}

func (b0 GetCredentialsRequest_builder) Build() *GetCredentialsRequest {
	m0 := &GetCredentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_LinkId = b.LinkId
	}
	return m0
}

type GetCredentialsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Credentials map[string]string      `protobuf:"bytes,1,rep,name=credentials" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCredentialsResponse) Reset() {
	*x = GetCredentialsResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsResponse) ProtoMessage() {}

func (x *GetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCredentialsResponse) GetCredentials() map[string]string {
	if x != nil {
		return x.xxx_hidden_Credentials
	}
	return nil
}

func (x *GetCredentialsResponse) SetCredentials(v map[string]string) {
	x.xxx_hidden_Credentials = v
}

type GetCredentialsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Credentials map[string]string
}

func (b0 GetCredentialsResponse_builder) Build() *GetCredentialsResponse {
	m0 := &GetCredentialsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Credentials = b.Credentials
	return m0
}

type DeleteCredentialsRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId       *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	xxx_hidden_AllowMissing bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DeleteCredentialsRequest) Reset() {
	*x = DeleteCredentialsRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialsRequest) ProtoMessage() {}

func (x *DeleteCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteCredentialsRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *DeleteCredentialsRequest) GetAllowMissing() bool {
	if x != nil {
		return x.xxx_hidden_AllowMissing
	}
	return false
}

func (x *DeleteCredentialsRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeleteCredentialsRequest) SetAllowMissing(v bool) {
	x.xxx_hidden_AllowMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteCredentialsRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteCredentialsRequest) HasAllowMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteCredentialsRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

func (x *DeleteCredentialsRequest) ClearAllowMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllowMissing = false
}

type DeleteCredentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId       *string
	AllowMissing *bool
}

func (b0 DeleteCredentialsRequest_builder) Build() *DeleteCredentialsRequest {
	m0 := &DeleteCredentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_LinkId = b.LinkId
	}
	if b.AllowMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AllowMissing = *b.AllowMissing
	}
	return m0
}

type DeleteCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialsResponse) Reset() {
	*x = DeleteCredentialsResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialsResponse) ProtoMessage() {}

func (x *DeleteCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteCredentialsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteCredentialsResponse_builder) Build() *DeleteCredentialsResponse {
	m0 := &DeleteCredentialsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SetMetadataRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId      *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	xxx_hidden_Metadata    map[string]string      `protobuf:"bytes,2,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetMetadataRequest) Reset() {
	*x = SetMetadataRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetadataRequest) ProtoMessage() {}

func (x *SetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetMetadataRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *SetMetadataRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *SetMetadataRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SetMetadataRequest) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *SetMetadataRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetMetadataRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

type SetMetadataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId   *string
	Metadata map[string]string
}

func (b0 SetMetadataRequest_builder) Build() *SetMetadataRequest {
	m0 := &SetMetadataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_LinkId = b.LinkId
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type SetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMetadataResponse) Reset() {
	*x = SetMetadataResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetadataResponse) ProtoMessage() {}

func (x *SetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SetMetadataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SetMetadataResponse_builder) Build() *SetMetadataResponse {
	m0 := &SetMetadataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetMetadataRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId      *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMetadataRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *GetMetadataRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetMetadataRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetMetadataRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

type GetMetadataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId *string
}

func (b0 GetMetadataRequest_builder) Build() *GetMetadataRequest {
	m0 := &GetMetadataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_LinkId = b.LinkId
	}
	return m0
}

type GetMetadataResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata map[string]string      `protobuf:"bytes,1,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMetadataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *GetMetadataResponse) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

type GetMetadataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata map[string]string
}

func (b0 GetMetadataResponse_builder) Build() *GetMetadataResponse {
	m0 := &GetMetadataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type DeleteMetadataRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinkId       *string                `protobuf:"bytes,1,opt,name=link_id,json=linkId"`
	xxx_hidden_AllowMissing bool                   `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DeleteMetadataRequest) Reset() {
	*x = DeleteMetadataRequest{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetadataRequest) ProtoMessage() {}

func (x *DeleteMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteMetadataRequest) GetLinkId() string {
	if x != nil {
		if x.xxx_hidden_LinkId != nil {
			return *x.xxx_hidden_LinkId
		}
		return ""
	}
	return ""
}

func (x *DeleteMetadataRequest) GetAllowMissing() bool {
	if x != nil {
		return x.xxx_hidden_AllowMissing
	}
	return false
}

func (x *DeleteMetadataRequest) SetLinkId(v string) {
	x.xxx_hidden_LinkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeleteMetadataRequest) SetAllowMissing(v bool) {
	x.xxx_hidden_AllowMissing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteMetadataRequest) HasLinkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteMetadataRequest) HasAllowMissing() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteMetadataRequest) ClearLinkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_LinkId = nil
}

func (x *DeleteMetadataRequest) ClearAllowMissing() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AllowMissing = false
}

type DeleteMetadataRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LinkId       *string
	AllowMissing *bool
}

func (b0 DeleteMetadataRequest_builder) Build() *DeleteMetadataRequest {
	m0 := &DeleteMetadataRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LinkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_LinkId = b.LinkId
	}
	if b.AllowMissing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AllowMissing = *b.AllowMissing
	}
	return m0
}

type DeleteMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMetadataResponse) Reset() {
	*x = DeleteMetadataResponse{}
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetadataResponse) ProtoMessage() {}

func (x *DeleteMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thrippy_v1_thrippy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteMetadataResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteMetadataResponse_builder) Build() *DeleteMetadataResponse {
	m0 := &DeleteMetadataResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_thrippy_v1_thrippy_proto protoreflect.FileDescriptor

const file_thrippy_v1_thrippy_proto_rawDesc = "" +
	"\n" +
	"\x18thrippy/v1/thrippy.proto\x12\n" +
	"thrippy.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a!google/protobuf/go_features.proto\x1a\x1cthrippy/v1/credentials.proto\x1a\x16thrippy/v1/oauth.proto\"t\n" +
	"\x11CreateLinkRequest\x12\x1f\n" +
	"\btemplate\x18\x01 \x01(\tB\x03\xe0A\x02R\btemplate\x12>\n" +
	"\foauth_config\x18\x02 \x01(\v2\x17.thrippy.v1.OAuthConfigB\x02(\x01R\voauthConfig\"w\n" +
	"\x12CreateLinkResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12H\n" +
	"\x11credential_fields\x18\x02 \x03(\v2\x1b.thrippy.v1.CredentialFieldR\x10credentialFields\".\n" +
	"\x0eGetLinkRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\"\xb7\x01\n" +
	"\x0fGetLinkResponse\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12>\n" +
	"\foauth_config\x18\x02 \x01(\v2\x17.thrippy.v1.OAuthConfigB\x02(\x01R\voauthConfig\x12H\n" +
	"\x11credential_fields\x18\x03 \x03(\v2\x1b.thrippy.v1.CredentialFieldR\x10credentialFields\"V\n" +
	"\x11DeleteLinkRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\x14\n" +
	"\x12DeleteLinkResponse\"\xfe\x01\n" +
	"\x15SetCredentialsRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\x12X\n" +
	"\rgeneric_creds\x18\x02 \x03(\v23.thrippy.v1.SetCredentialsRequest.GenericCredsEntryR\fgenericCreds\x12,\n" +
	"\x05token\x18\x03 \x01(\v2\x16.thrippy.v1.OAuthTokenR\x05token\x1a?\n" +
	"\x11GenericCredsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16SetCredentialsResponse\"5\n" +
	"\x15GetCredentialsRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\"\xaf\x01\n" +
	"\x16GetCredentialsResponse\x12U\n" +
	"\vcredentials\x18\x01 \x03(\v23.thrippy.v1.GetCredentialsResponse.CredentialsEntryR\vcredentials\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x18DeleteCredentialsRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\x1b\n" +
	"\x19DeleteCredentialsResponse\"\xb9\x01\n" +
	"\x12SetMetadataRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\x12H\n" +
	"\bmetadata\x18\x02 \x03(\v2,.thrippy.v1.SetMetadataRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13SetMetadataResponse\"2\n" +
	"\x12GetMetadataRequest\x12\x1c\n" +
	"\alink_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06linkId\"\x9d\x01\n" +
	"\x13GetMetadataResponse\x12I\n" +
	"\bmetadata\x18\x01 \x03(\v2-.thrippy.v1.GetMetadataResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x15DeleteMetadataRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\x18\n" +
	"\x16DeleteMetadataResponse2\xc1\b\n" +
	"\x0eThrippyService\x12a\n" +
	"\n" +
	"CreateLink\x12\x1d.thrippy.v1.CreateLinkRequest\x1a\x1e.thrippy.v1.CreateLinkResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/links\x12_\n" +
	"\aGetLink\x12\x1a.thrippy.v1.GetLinkRequest\x1a\x1b.thrippy.v1.GetLinkResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/links/{link_id}\x12h\n" +
	"\n" +
	"DeleteLink\x12\x1d.thrippy.v1.DeleteLinkRequest\x1a\x1e.thrippy.v1.DeleteLinkResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/links/{link_id}\x12\x83\x01\n" +
	"\x0eSetCredentials\x12!.thrippy.v1.SetCredentialsRequest\x1a\".thrippy.v1.SetCredentialsResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/links/{link_id}/credentials\x12\x80\x01\n" +
	"\x0eGetCredentials\x12!.thrippy.v1.GetCredentialsRequest\x1a\".thrippy.v1.GetCredentialsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/links/{link_id}/credentials\x12\x89\x01\n" +
	"\x11DeleteCredentials\x12$.thrippy.v1.DeleteCredentialsRequest\x1a%.thrippy.v1.DeleteCredentialsResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/links/{link_id}/credentials\x12w\n" +
	"\vSetMetadata\x12\x1e.thrippy.v1.SetMetadataRequest\x1a\x1f.thrippy.v1.SetMetadataResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/v1/links/{link_id}/metadata\x12t\n" +
	"\vGetMetadata\x12\x1e.thrippy.v1.GetMetadataRequest\x1a\x1f.thrippy.v1.GetMetadataResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/links/{link_id}/metadata\x12}\n" +
	"\x0eDeleteMetadata\x12!.thrippy.v1.DeleteMetadataRequest\x1a\".thrippy.v1.DeleteMetadataResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/links/{link_id}/metadataB3Z)github.com/tzrikka/thrippy-api/thrippy/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_thrippy_v1_thrippy_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_thrippy_v1_thrippy_proto_goTypes = []any{
	(*CreateLinkRequest)(nil),         // 0: thrippy.v1.CreateLinkRequest
	(*CreateLinkResponse)(nil),        // 1: thrippy.v1.CreateLinkResponse
	(*GetLinkRequest)(nil),            // 2: thrippy.v1.GetLinkRequest
	(*GetLinkResponse)(nil),           // 3: thrippy.v1.GetLinkResponse
	(*DeleteLinkRequest)(nil),         // 4: thrippy.v1.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),        // 5: thrippy.v1.DeleteLinkResponse
	(*SetCredentialsRequest)(nil),     // 6: thrippy.v1.SetCredentialsRequest
	(*SetCredentialsResponse)(nil),    // 7: thrippy.v1.SetCredentialsResponse
	(*GetCredentialsRequest)(nil),     // 8: thrippy.v1.GetCredentialsRequest
	(*GetCredentialsResponse)(nil),    // 9: thrippy.v1.GetCredentialsResponse
	(*DeleteCredentialsRequest)(nil),  // 10: thrippy.v1.DeleteCredentialsRequest
	(*DeleteCredentialsResponse)(nil), // 11: thrippy.v1.DeleteCredentialsResponse
	(*SetMetadataRequest)(nil),        // 12: thrippy.v1.SetMetadataRequest
	(*SetMetadataResponse)(nil),       // 13: thrippy.v1.SetMetadataResponse
	(*GetMetadataRequest)(nil),        // 14: thrippy.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),       // 15: thrippy.v1.GetMetadataResponse
	(*DeleteMetadataRequest)(nil),     // 16: thrippy.v1.DeleteMetadataRequest
	(*DeleteMetadataResponse)(nil),    // 17: thrippy.v1.DeleteMetadataResponse
	nil,                               // 18: thrippy.v1.SetCredentialsRequest.GenericCredsEntry
	nil,                               // 19: thrippy.v1.GetCredentialsResponse.CredentialsEntry
	nil,                               // 20: thrippy.v1.SetMetadataRequest.MetadataEntry
	nil,                               // 21: thrippy.v1.GetMetadataResponse.MetadataEntry
	(*OAuthConfig)(nil),               // 22: thrippy.v1.OAuthConfig
	(*CredentialField)(nil),           // 23: thrippy.v1.CredentialField
	(*OAuthToken)(nil),                // 24: thrippy.v1.OAuthToken
}
var file_thrippy_v1_thrippy_proto_depIdxs = []int32{
	22, // 0: thrippy.v1.CreateLinkRequest.oauth_config:type_name -> thrippy.v1.OAuthConfig
	23, // 1: thrippy.v1.CreateLinkResponse.credential_fields:type_name -> thrippy.v1.CredentialField
	22, // 2: thrippy.v1.GetLinkResponse.oauth_config:type_name -> thrippy.v1.OAuthConfig
	23, // 3: thrippy.v1.GetLinkResponse.credential_fields:type_name -> thrippy.v1.CredentialField
	18, // 4: thrippy.v1.SetCredentialsRequest.generic_creds:type_name -> thrippy.v1.SetCredentialsRequest.GenericCredsEntry
	24, // 5: thrippy.v1.SetCredentialsRequest.token:type_name -> thrippy.v1.OAuthToken
	19, // 6: thrippy.v1.GetCredentialsResponse.credentials:type_name -> thrippy.v1.GetCredentialsResponse.CredentialsEntry
	20, // 7: thrippy.v1.SetMetadataRequest.metadata:type_name -> thrippy.v1.SetMetadataRequest.MetadataEntry
	21, // 8: thrippy.v1.GetMetadataResponse.metadata:type_name -> thrippy.v1.GetMetadataResponse.MetadataEntry
	0,  // 9: thrippy.v1.ThrippyService.CreateLink:input_type -> thrippy.v1.CreateLinkRequest
	2,  // 10: thrippy.v1.ThrippyService.GetLink:input_type -> thrippy.v1.GetLinkRequest
	4,  // 11: thrippy.v1.ThrippyService.DeleteLink:input_type -> thrippy.v1.DeleteLinkRequest
	6,  // 12: thrippy.v1.ThrippyService.SetCredentials:input_type -> thrippy.v1.SetCredentialsRequest
	8,  // 13: thrippy.v1.ThrippyService.GetCredentials:input_type -> thrippy.v1.GetCredentialsRequest
	10, // 14: thrippy.v1.ThrippyService.DeleteCredentials:input_type -> thrippy.v1.DeleteCredentialsRequest
	12, // 15: thrippy.v1.ThrippyService.SetMetadata:input_type -> thrippy.v1.SetMetadataRequest
	14, // 16: thrippy.v1.ThrippyService.GetMetadata:input_type -> thrippy.v1.GetMetadataRequest
	16, // 17: thrippy.v1.ThrippyService.DeleteMetadata:input_type -> thrippy.v1.DeleteMetadataRequest
	1,  // 18: thrippy.v1.ThrippyService.CreateLink:output_type -> thrippy.v1.CreateLinkResponse
	3,  // 19: thrippy.v1.ThrippyService.GetLink:output_type -> thrippy.v1.GetLinkResponse
	5,  // 20: thrippy.v1.ThrippyService.DeleteLink:output_type -> thrippy.v1.DeleteLinkResponse
	7,  // 21: thrippy.v1.ThrippyService.SetCredentials:output_type -> thrippy.v1.SetCredentialsResponse
	9,  // 22: thrippy.v1.ThrippyService.GetCredentials:output_type -> thrippy.v1.GetCredentialsResponse
	11, // 23: thrippy.v1.ThrippyService.DeleteCredentials:output_type -> thrippy.v1.DeleteCredentialsResponse
	13, // 24: thrippy.v1.ThrippyService.SetMetadata:output_type -> thrippy.v1.SetMetadataResponse
	15, // 25: thrippy.v1.ThrippyService.GetMetadata:output_type -> thrippy.v1.GetMetadataResponse
	17, // 26: thrippy.v1.ThrippyService.DeleteMetadata:output_type -> thrippy.v1.DeleteMetadataResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_thrippy_v1_thrippy_proto_init() }
func file_thrippy_v1_thrippy_proto_init() {
	if File_thrippy_v1_thrippy_proto != nil {
		return
	}
	file_thrippy_v1_credentials_proto_init()
	file_thrippy_v1_oauth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thrippy_v1_thrippy_proto_rawDesc), len(file_thrippy_v1_thrippy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thrippy_v1_thrippy_proto_goTypes,
		DependencyIndexes: file_thrippy_v1_thrippy_proto_depIdxs,
		MessageInfos:      file_thrippy_v1_thrippy_proto_msgTypes,
	}.Build()
	File_thrippy_v1_thrippy_proto = out.File
	file_thrippy_v1_thrippy_proto_goTypes = nil
	file_thrippy_v1_thrippy_proto_depIdxs = nil
}
