[project]
name = "thrippy"
version = "1.0.0"
description = "Generated code for Thrippy gRPC clients"
readme = "README.md"
authors = [
    { name = "Daniel Abraham", email = "aeroquix@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "grpcio~=1.78",
]

[build-system]
requires = ["uv_build~=0.10"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "grpcio-tools~=1.78",
]
